version: "2"
services:
  gitlab:
    image: epflsti/gitlab-docker
    hostname: gitlab
    domainname: epfl.ch
    build: gitlab-main
    volumes:
      - "/srv/gitlab/secrets/ssh/ssh_host_dsa_key:/etc/gitlab/ssh_host_dsa_key:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_dsa_key.pub:/etc/gitlab/ssh_host_dsa_key.pub:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_key:/etc/gitlab/ssh_host_key:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_key.pub:/etc/gitlab/ssh_host_key.pub:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_ecdsa_key:/etc/gitlab/ssh_host_ecdsa_key:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_ecdsa_key.pub:/etc/gitlab/ssh_host_ecdsa_key.pub:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_ed25519_key:/etc/gitlab/ssh_host_ed25519_key:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_ed25519_key.pub:/etc/gitlab/ssh_host_ed25519_key.pub:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_rsa_key:/etc/gitlab/ssh_host_rsa_key:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_rsa_key.pub:/etc/gitlab/ssh_host_rsa_key.pub:ro"
      - "/srv/gitlab/secrets/gitlab-secrets.json:/etc/gitlab/gitlab-secrets.json"
      - "./gitlab-main/config/gitlab.rb:/etc/gitlab/gitlab.rb"
      - "/srv/gitlab/backup:/var/opt/gitlab/backups"
      - "/srv/gitlab/data/git-data:/var/opt/gitlab/git-data"
      - "/srv/gitlab/data/ssh_user_public_keys:/var/opt/gitlab/.ssh"
      - "/srv/gitlab/data/shared:/var/opt/gitlab/gitlab-rails/shared"
      - "/srv/gitlab/data/uploads:/var/opt/gitlab/gitlab-rails/uploads"
      - "/srv/gitlab/data/gitlab-ci/builds:/var/opt/gitlab/gitlab-ci/builds"
      # Make visible the UNIX domain sockets of the shared DB containers below:
      - "/srv/gitlab/run/redis-socket:/var/opt/gitlab/redis"
      - "/srv/gitlab/run/postgres-socket:/var/opt/gitlab/postgresql"
  postgresql:
    image: postgres:9.6
    volumes:
      - "/srv/gitlab/postgresql/data:/var/lib/postgresql/data"
      - "/srv/gitlab/logs/postgresql:/var/log"
      - "/srv/gitlab/run/postgres-socket/:/run/postgresql/"
      - "/srv/gitlab/config/postgresql/passwd:/etc/passwd"
  redis:
    image: redis:latest
    volumes:
      - "/srv/gitlab/config/redis:/usr/local/etc/redis"
      - "/srv/gitlab/run/redis-socket:/run/redis"
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
  frontend:
    image: nginx
    container_name: gitlabdocker_frontend  # Single instance, not scalable
    volumes:
      - "/srv/gitlab/ssl:/etc/ssl"
      - "./frontend/nginx.conf.tt:/etc/nginx/nginx.conf.tt:ro"
      - "./frontend:/assets"
    ports:
      - "443:443"
      - "22:22"
    environment:
      - ENVIRONMENT=prod
    command: /assets/nginx-wrangler /etc/nginx/nginx.conf.tt
  frontend_staging:
    image: nginx
    container_name: gitlabdocker_frontend_staging  # Single instance, not scalable
    volumes:
      - "/srv/gitlab/ssl:/etc/ssl"
      - "./frontend/nginx.conf.tt:/etc/nginx/nginx.conf.tt:ro"
      - "./frontend:/assets"
    ports:
      - "444:443"
      - "23:22"
    environment:
      - ENVIRONMENT=staging
    command: /assets/nginx-wrangler /etc/nginx/nginx.conf.tt
  redirect:
    image: quay.io/coreos/nginx-https-redirect
    ports:
      - "80:80"
  plantuml:
    image: webvariants/plantuml-server
